Rspec課題4 修正
14m3185yoshi/rspec_app_exam pull request #2
Opened 2020-09-15 01:26 UTC by 14m3185yoshi

確認よろしくお願いします。

2020-09-15 02:32 UTC, yuji91 commented on spec/system/task_spec.rb
> +      fit 'Project詳細からTask一覧ページにアクセスした場合、Taskが表示されること' do
focusの指定がついたままになっています。

2020-09-15 02:33 UTC, yuji91 commented on spec/system/task_spec.rb
>          expect(page).to have_content 'title100'
このtitle100の記載は必要ですか？

2020-09-15 02:38 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(find('.task_list')).to have_content(Time.current.strftime('%-m/%d %-H:%M'))
時刻のフォーマットを確認するというのは正しいですが、このままだとView側の時刻表示の仕様が変わった際にテストが落ちてしまいます。
Viewで使用されているメソッドを使うようにしましょう。

2020-09-15 02:44 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(page).to_not have_content task.title
factoryの内容に依存しているため、factoryの値が変わってしまうとまたテストが落ちてしまう可能性があります。

2020-09-15 02:45 UTC, yuji91 requested changes
PullRequestの概要欄に何を記載した方がいいか、考えてみてください。

コミットメッセージが「修正」とだけ記載されていても、それがどのような意図の修正なのか分かりません。適切な単位で適切なコミットメッセージを記載するようにしてください。

また、 #1 にレビューで指摘事項を送っています。この内容について回答していないものがあれば返信をお願いします。

2020-09-18 09:56 UTC, merged

2020-09-18 12:16 UTC, 14m3185yoshi commented on spec/system/task_spec.rb
> +        expect(current_path).to eq project_tasks_path(project)
Application_helperで読み込みんだメソッドを使い、ビューで変更がかかったさいにも対応するように変更。

2020-09-18 12:19 UTC, 14m3185yoshi commented on spec/system/task_spec.rb
> +        expect(find('.task_list')).to_not have_content task.title
```
find('.task_list')
```
で対象を絞る。

2020-09-18 12:23 UTC, 14m3185yoshi commented
pageオブジェクトをbinding.irbで確認しました！
page.methodsコマンドで使えるメソッドを確認しながらいろいろ試してみました。


あと間違えてmergeしてしまいました。
何度もすみませんでした。

2020-09-18 16:08 UTC, yuji91 commented
> 適切な単位で適切なコミットメッセージを記載するようにしてください。

この指摘に対してはどのように対応したか、ご回答お願いします。